version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be_bm_fast_api
    ports:
      - "4568:3897"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - bm_network

networks:
  bm_network:
    driver: bridge

volumes:
  postgres_data: 